name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          HASH: $(git rev-parse --short "$GITHUB_SHA")
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/**.jar

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: format
        run: ./gradlew spotlessCheck