name: publish to modrinth

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Upload a neoforge build
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/**.jar
          name: neoforge
          retention-days: 2

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: neoforge
          path: download

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: xxxx
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          changelog-file: CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: neoforge
          game-versions: 1.20.4
          modrinth-dependencies: |
            ae2 | depends
            applied-energistics-2-wireless-terminals | depends
          java: 17
          version: ${{ env.version_name }}
          name: ${{ env.version_name }}
          files: download/!(*-@(dev|dev-shadow|sources)).jar